### ISSUE TITLE
Upgrade to Qualimap 2.0

### ISSUE THREAD

**Issue by parlundin** [NationalGenomicsInfrastructure/piper#44]
Qualimap bamQC terminates with ArrayIndexOutOfBoundsException when to many reads. This issue should be fixed in latest version of Qualimap 2.0 

```java.lang.ArrayIndexOutOfBoundsException: -452499825
	at java.util.ArrayList.elementData(ArrayList.java:371)
	at java.util.ArrayList.get(ArrayList.java:384)
	at org.bioinfo.ngs.qc.qualimap.beans.BamStats.computeInsertSizeHistogram(BamStats.java:975)
	at org.bioinfo.ngs.qc.qualimap.beans.BamStats.computeHistograms(BamStats.java:793)
	at org.bioinfo.ngs.qc.qualimap.process.BamStatsAnalysis.run(BamStatsAnalysis.java:488)
	at org.bioinfo.ngs.qc.qualimap.main.BamQcTool.execute(BamQcTool.java:211)
	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:177)
	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:102)```

**Comment by johandahlberg** [comment]
I think that this should be fixed now. Will wait for confirmation from @parlundin, and then I'll close this.
